# veda_desktop.py
import streamlit as st
import os
import time
from pathlib import Path
from datetime import datetime
from PIL import Image

# Veda Core Imports
from brain import VedaBrain
from memory.history import init_database, save_message, get_recent_messages, get_all_notes
from memory.semantic import SemanticMemory

# Page Configuration
st.set_page_config(
    page_title="Veda🧠Ready",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS ---
st.markdown("""
<style>
    .stChatMessage {
        border-radius: 15px;
        padding: 10px;
        margin-bottom: 10px;
    }
    .stActionButton {
        background-color: #2ecc71;
        color: white;
    }
    .main {
        background-color: #0e1117;
    }
    .sidebar .sidebar-content {
        background-color: #1a1c24;
    }
</style>
""", unsafe_allow_html=True)

# --- INITIALIZATION ---
if "session_id" not in st.session_state:
    st.session_state.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    init_database()

if "brain" not in st.session_state:
    with st.spinner("Initializing Veda Brain..."):
        st.session_state.brain = VedaBrain(model="qwen2.5:7b")

if "messages" not in st.session_state:
    # Load recent history from DB
    history = get_recent_messages(limit=20)
    st.session_state.messages = history if history else []

# --- SIDEBAR: Control Panel ---
with st.sidebar:
    st.title("Veda🧠Ready")
    st.caption("INDUSTRIALIZING ENGINEERING DESIGN")
    st.divider()
    
    # Model Selection
    st.subheader("Model Configuration")
    try:
        models_resp = st.session_state.brain.client.list()
        models = models_resp.get('models', []) if isinstance(models_resp, dict) else models_resp.models
        model_names = [m.get('name') if isinstance(m, dict) else m.model for m in models]
        
        current_idx = model_names.index(st.session_state.brain.model) if st.session_state.brain.model in model_names else 0
        new_model = st.selectbox("Active Brain:", model_names, index=current_idx)
        if new_model != st.session_state.brain.model:
            st.session_state.brain.model = new_model
            st.success(f"Switched to {new_model}")
    except:
        st.error("Ollama connection failed.")

    st.divider()
    
    # System Status
    st.subheader("System Status")
    st.success("Core Logic: ONLINE")
    mcp_count = len(st.session_state.brain.mcp_manager.clients)
    st.info(f"MCP Servers: {mcp_count} Active")
    
    # Initialization Errors
    if st.session_state.brain.init_errors:
        with st.expander("⚠️ System Warnings"):
            for err in st.session_state.brain.init_errors:
                st.warning(err)

    st.divider()
    
    # Workspace Quick View
    st.subheader("Workspace")
    workspace_files = list(Path("workspace").glob("*.*"))
    if workspace_files:
        for f in workspace_files[:5]:
            st.text(f"📄 {f.name}")
    else:
        st.caption("Workspace is empty.")

    if st.button("Clear Conversation"):
        st.session_state.messages = []
        st.rerun()

# --- MAIN CHAT INTERFACE ---

# Display chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        # If message contains a path to an image generated by Veda, try to render it
        if ".png" in message["content"] or ".jpg" in message["content"]:
            # Basic detection logic
            import re
            img_paths = re.findall(r'([A-Za-z0-9_/\]+\.(?:png|jpg))', message["content"])
            for path in img_paths:
                if os.path.exists(path):
                    st.image(path, caption=f"Generated Visual: {path}")

# Chat Input
if prompt := st.chat_input("Ask Veda to design, calculate, or research..."):
    # 1. User Message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
    
    save_message("user", prompt, st.session_state.session_id)

    # 2. Veda Thinking & Response
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        full_response = ""
        
        # We use the recursive brain logic but wrap it for Streamlit
        with st.status("Veda is thinking...", expanded=False) as status:
            # First pass: Thought + Potential Tool Call
            for chunk in st.session_state.brain.stream_think(prompt):
                full_response += chunk
                response_placeholder.markdown(full_response + "▌")
            
            # Handle recursive tools if present
            if "TOOL:" in full_response:
                status.update(label="Executing Agentic Tools...", state="running", expanded=True)
                final_answer = st.session_state.brain._handle_tool_calls(full_response, prompt)
                full_response = final_answer
                response_placeholder.markdown(full_response)
            
            status.update(label="Task Complete", state="complete", expanded=False)

        st.session_state.messages.append({"role": "assistant", "content": full_response})
        
        # Check for image generation in final response
        import re
        img_paths = re.findall(r'([A-Za-z0-9_/\]+\.(?:png|jpg))', full_response)
        for path in img_paths:
            if os.path.exists(path):
                st.image(path, caption=f"Generated Visual: {path}")

    # No need to manually save assistant message here as brain.think/stream_think already saves to session
